#!/bin/bash

# bit overkill but there may be more checks in the future
ret=0
pgrep -f /usr/sbin/kojid > /dev/null; (( ret = ret || $? ))
nslookup "$KOJI_HUB" > /dev/null; (( ret = ret || $? ))
curl -LSs -o /dev/null "https://${KOJI_HUB}/koji"; (( ret = ret || $? ))
exit $ret
